version: "3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80" # Exposición HTTP
      #- "443:443"     # Exposición HTTPS (opcional)
      - "8080:8080" # Dashboard de Traefik
    command:
      - "--api.insecure=true" # Habilita el dashboard de Traefik sin seguridad
      - "--providers.docker=true" # Habilita el soporte de Docker
      - "--providers.docker.exposedbydefault=false" # Solo exponer servicios con label
      - "--entrypoints.web.address=:80" # Entrada para HTTP
      #- "--entrypoints.websecure.address=:443"      # Entrada para HTTPS (opcional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Montar el socket de Docker
    networks:
      - kqt-web

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kqt-web

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kqt-web

  kqt-producer:
    image: kqt-producer:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    labels:
      - "traefik.enable=true" # Habilita Traefik para este servicio
      - "traefik.http.routers.kqt-producer.rule=Host(`kqt-producer.localhost`)"
      - "traefik.http.services.kqt-producer.loadbalancer.server.port=8080"
    networks:
      - kqt-web

networks:
  kqt-web:
    driver: bridge
